### ISSUE TITLE
画廊详情页解析失败

### ISSUE THREAD

**Issue by sunbeams001** [exzhawk/EhViewer#32]
**简略描述 / Describe the bug**
解析失败，画廊列表正常，画廊详情报错，应该是网站改了一些东西

**如何重现 / To Reproduce**
重现的步骤：
1. 直接打开任意画廊详情
2. 出现报错页面

**预期行为 / Expected behavior**
正常显示

**截图 / Screenshots**
NaN

**设备型号与 Android 版本 / Device model and Android version**
 - 设备型号：Redmi K50U
 - Android 版本：Android 12

**备注 / Additional context**

**Comment by uNderdog101** [comment]
Using Google Translate I'm assuming this is the "parse error" I am also getting. I found a temporary workaround; in the settings for EH, change the gallery site from Exhentai to E-Hentai. Less content, but it works again.

**Comment by exzhawk** [comment]
Fixed in 1.7.21

**Comment by Linnest2020** [comment]
**简略描述 / Describe the bug**
大概说下是什么问题。
解析失败，画廊列表正常，画廊详情报错，里站应该也修改了
1.7.21也没有完全修复

**如何重现 / To Reproduce**
重现的步骤：
1. 切换至里站
2. 直接打开任意画廊详情
3. 出现报错页面

**预期行为 / Expected behavior**
应该是什么样子的？
和表站一样正常显示

**截图 / Screenshots**
能截图的话就发截图，请注意风序良俗。
NaN

**设备型号与 Android 版本 / Device model and Android version**
 - 设备型号：PHP110
 - Android 版本：14
 - 已经更新至 1.7.21

**备注 / Additional context**
还有什么想说的？
这个是里站的问题？
